name: Run tests

on: [push]
jobs:
    test:
        name: "Run tests and build"
        runs-on: "ubuntu-latest"
        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v4
            - name: 'Setup python'
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: 'Install pip and run test suite'
              run: |
                pip install hatch
                hatch run test
                hatch run types:check
                hatch build
